### ISSUE TITLE
"Axe Spawner" does not contain a definition for "Game"

### ISSUE THREAD

**Issue by CloudooDoggo** [mahuvrc/VRCAxeThrowing#1]
Not sure why I always see this issue but I tried making a new project and it didn't work again.

I really love this game and I'd love to have it in my world someday.

**Comment by saberslay** [comment]
I would love to have it in my world someday as well.
![Axe Spawner does not contain a definition for Game](https://user-images.githubusercontent.com/4098559/151236130-0691ce90-c1c8-4209-9475-502955bea5c8.png)

**Comment by mahuvrc** [comment]
Hey guys sorry it's been a while since I took a look at this page. Issue was the AxeSpawner script was missing a U# program asset in the unitypackage I uploaded. I updated the release so it now includes that asset as well.
