### ISSUE TITLE
Axe Throwing Game mode does not contain a definition for "Game"

### ISSUE THREAD

**Issue by saberslay** [mahuvrc/VRCAxeThrowing#2]
![Screenshot 2022-05-10 013747](https://user-images.githubusercontent.com/4098559/167520167-cac238a0-5173-41ac-b6b6-9c362dd7fb66.png)

**Comment by mahuvrc** [comment]
You need to use the old [version 1.0.1](https://github.com/mahuvrc/VRCAxeThrowing/releases/tag/v1.0.1) in your project.

Version 2.x This prefab uses U# v1.0.0b12
You're importing version 2.1.1 into a project probably using U# 0.20.3 or older which is not supported.
