### ISSUE TITLE
Prefabs missing

### ISSUE THREAD

**Issue by EnglishDave22** [mahuvrc/VRCAxeThrowing#3]
Hi there! 

Making a world and I love the idea of your axe game!! Def want it in!

I dragged over the prefab of the game and some of the assets are missing from the package. I can get the wood board and the texture put up, but there is no surface to place the target on and sadly, there doesn't seem to be a place to pop the target textures. 

please see attached screenshot
![image](https://user-images.githubusercontent.com/117280686/199489468-8cac9471-0b47-4319-8a3d-0eedbb35e81c.png)

Anything obvious I'm missing?

**Comment by mahuvrc** [comment]
The missing prefabs are models that I made in blender. You'll need to have an install of blender that unity can use to import them I guess. If you have blender installed, unity should import them automatically.

**Comment by EnglishDave22** [comment]
ahhhhhhhh! 

Sorry I'm new. Thank you!
